import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/sidebar'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body className={`min-h-screen ${inter.className}`}>
        <Navbar />
        <main className='flex max-w-screen-2xl mx-auto'>
          <Sidebar />
          <div className='lg:ml-72 pt-[73px] w-full overflow-hidden'>
            <div className='px-4 lg:px-6 py-8'>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html >
  )
}
